# SUMA
Title: Suma sobre Dios, el hombre, la fe, el alma, la sustancia, el cuerpo, el entendimiento, y la contingencia
author: 
 name: Fernanda Carreto
 email: fcerey@gmail.com
Description: En el siguiente texto se hablaran de los temas hablados en el titulo de manera breve desde la perspectiva de Hildegarda, Aquino, y al-Fâräbí.  
